# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rateable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Client name')),
                ('bith_date', models.DateField(default='01/01/1970')),
                ('city', models.TextField(default='Client city')),
                ('country', models.TextField(default='Client country')),
                ('mail', models.EmailField(default='client@email.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Category')),
                ('rateable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Rateable')),
            ],
        ),
    ]
